title: Bem-vindo ao blog
author: GabrielBzl
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Essa é a descrição do blog
theme: jekyll-theme-hacker
# social links
twitter_username: yasdasd # DO NOT include the @ character, or else the build will fail!
github_username:  yasdasdhandle # DO NOT include the @ character, or else the build will fail!
#close 2
show_excerpts: true # set to false to remove excerpts on the homepage
