title: My title
author: Gbb
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Bla bla bla
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!
#close 2
show_excerpts: true # set to false to remove excerpts on the homepage
